#!/usr/bin/env python3
"""Scan runs/max*_*/ directories and rebuild backbone.md with per-dataset
backbone comparisons (val_f1 / test@bv / test+TTA / gap to fair SOTA).

Auto-discovers any prefix matching `max<tag>_<dataset>_<timestamp>` so adding
a new sweep (e.g. maxdinov3) requires no code change here. Picks the newest
run per (backbone-tag, dataset) pair.
"""

from __future__ import annotations
import csv
import json
import re
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RUNS = ROOT / "runs"
OUT = ROOT / "backbone.md"

# Fair SOTA F1 per dataset (no extra CD data, no synthetic, no joint training).
SOTA = {
    "cdd":           (96.12, "RFL-CDNet (2024)"),
    "dsifn_cd":      (96.65, "DDPM-CD (2024)"),
    "levir_cd":      (90.24, "ChangeFormer (2022)"),
    "levir_cd_plus": (87.71, "DDCDNet (2024)"),
    "s2looking":     (68.60, "FIBTNet (2024)"),
    "second":        (72.46, "SAM-SCD (2025)"),
}

DATASETS = list(SOTA.keys())

RUN_RE = re.compile(r"^max(?P<tag>[a-zA-Z0-9]+)_(?P<ds>.+)_(?P<ts>\d{8}_\d{4})$")


def parse_run_dir(d: Path):
    m = RUN_RE.match(d.name)
    if not m:
        return None
    tag = m.group("tag")
    ds = m.group("ds")
    ts = m.group("ts")
    if ds not in SOTA:
        return None
    return tag, ds, ts


def find_inner_run(outer: Path) -> Path | None:
    """Each outer run dir has one or more timestamped subdirs; pick the newest."""
    subs = sorted([p for p in outer.iterdir() if p.is_dir()], reverse=True)
    return subs[0] if subs else None


def load_results(run: Path):
    cfg_path = run / "config.json"
    log_path = run / "log.csv"
    tta_path = run / "test_results.json"
    if not cfg_path.exists() or not log_path.exists():
        return None
    cfg = json.loads(cfg_path.read_text())
    rows = list(csv.DictReader(open(log_path)))
    if not rows:
        return None
    best = max(rows, key=lambda r: float(r.get("val_f1", 0) or 0))
    last = rows[-1]
    val_f1 = float(best["val_f1"]) * 100
    test_at_bv = float(best.get("test_f1", 0) or 0) * 100
    ep_bv = int(best["epoch"])
    ep_now = int(last["epoch"])
    plateau = ep_now - ep_bv
    tta = None
    if tta_path.exists():
        tta = float(json.loads(tta_path.read_text())["f1"]) * 100
    encoder = cfg.get("encoder", "?")
    decoder = cfg.get("decoder", "?")
    return {
        "encoder": encoder, "decoder": decoder,
        "val_f1": val_f1, "test_at_bv": test_at_bv, "tta": tta,
        "ep_bv": ep_bv, "ep_now": ep_now, "plateau": plateau,
    }


def build():
    # tag -> dataset -> (run_dir, results)
    by_tag: dict[str, dict[str, tuple[Path, dict]]] = {}
    for d in sorted(RUNS.iterdir()):
        if not d.is_dir():
            continue
        info = parse_run_dir(d)
        if info is None:
            continue
        tag, ds, ts = info
        inner = find_inner_run(d)
        if inner is None:
            continue
        res = load_results(inner)
        if res is None:
            continue
        # Keep only the most recent per (tag, ds) — d list is sorted alpha so
        # ts is naturally in order; the last one wins.
        by_tag.setdefault(tag, {})[ds] = (inner, res)

    if not by_tag:
        OUT.write_text("# Backbone Comparison\n\nNo runs found.\n")
        return

    tags_sorted = sorted(by_tag.keys())
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("# Backbone Comparison\n")
    lines.append(f"_Auto-generated by `scripts/update_backbone_md.py` — last update: {now}_\n")
    lines.append("Recipe (shared across runs): `--no_early_stop --ema 0.99 --cnn_skip --finetune_decoder --search_threshold` "
                 "with TTA at final eval. Dataset yamls use heavy aug for 256/512² datasets, minimal aug for 1024² "
                 "(see `configs/datasets/*_heavy.yaml`).\n")
    lines.append("Gap is `test+TTA - SOTA` in F1 percentage points (positive = beats fair SOTA).\n")

    # ---- Summary table: dataset rows × backbone-tag columns (test+TTA F1) ----
    lines.append("## Summary (test+TTA F1 per backbone)\n")
    header = ["Dataset", "Fair SOTA"] + [f"max-{t}" for t in tags_sorted] + ["Best (gap)"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")
    for ds in DATASETS:
        sota_val, sota_who = SOTA[ds]
        cells = [ds, f"{sota_val:.2f} ({sota_who.split()[0]})"]
        best_score = -1.0
        best_tag = None
        for t in tags_sorted:
            entry = by_tag.get(t, {}).get(ds)
            if entry is None:
                cells.append("—")
                continue
            res = entry[1]
            score = res["tta"] if res["tta"] is not None else res["test_at_bv"]
            tag_marker = "" if res["tta"] is not None else "*"
            cells.append(f"{score:.2f}{tag_marker}")
            if score > best_score:
                best_score = score
                best_tag = t
        if best_tag is None:
            cells.append("—")
        else:
            gap = best_score - sota_val
            sign = "+" if gap >= 0 else ""
            verdict = " ✅" if gap >= 0 else ""
            cells.append(f"max-{best_tag}: {sign}{gap:.2f}{verdict}")
        lines.append("| " + " | ".join(cells) + " |")
    lines.append("\n_`*` = per-epoch test (TTA not yet run; final test pending)._\n")

    # ---- Per-dataset detail tables ----
    lines.append("## Per-dataset detail\n")
    for ds in DATASETS:
        sota_val, sota_who = SOTA[ds]
        lines.append(f"### {ds}  (fair SOTA: {sota_val:.2f} — {sota_who})\n")
        lines.append("| Backbone | Encoder | Decoder | best_val | test@bv | test+TTA | gap | ep_bv / ep_now (plateau) |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for t in tags_sorted:
            entry = by_tag.get(t, {}).get(ds)
            if entry is None:
                continue
            run_dir, r = entry
            tta_str = f"{r['tta']:.2f}" if r["tta"] is not None else "—"
            score_for_gap = r["tta"] if r["tta"] is not None else r["test_at_bv"]
            gap = score_for_gap - sota_val
            sign = "+" if gap >= 0 else ""
            tta_marker = "" if r["tta"] is not None else " *"
            lines.append(
                f"| max-{t} | `{r['encoder']}` | `{r['decoder']}` | "
                f"{r['val_f1']:.2f} | {r['test_at_bv']:.2f} | {tta_str}{tta_marker} | "
                f"{sign}{gap:.2f} | {r['ep_bv']} / {r['ep_now']} (+{r['plateau']}ep) |"
            )
        lines.append("")
    lines.append("_`*` after a value = test+TTA pending; the gap uses per-epoch test as a placeholder._\n")

    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    build()
